In [1]:
import os

In [17]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from xgboost import XGBRegressor
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error , mean_squared_error , r2_score

In [4]:
!pip install xgboost

Collecting xgboost
  Downloading xgboost-2.1.3-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in c:\users\vinay\appdata\local\programs\python\python311\lib\site-packages (from xgboost) (1.24.3)
Requirement already satisfied: scipy in c:\users\vinay\appdata\local\programs\python\python311\lib\site-packages (from xgboost) (1.11.2)
Downloading xgboost-2.1.3-py3-none-win_amd64.whl (124.9 MB)
   ---------------------------------------- 0.0/124.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/124.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/124.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/124.9 MB ? eta -:--:--
   ---------------------------------------- 0.5/124.9 MB 1.7 MB/s eta 0:01:15
   ---------------------------------------- 1.0/124.9 MB 1.7 MB/s eta 0:01:14
    --------------------------------------- 1.8/124.9 MB 2.1 MB/s eta 0:00:58
    --------------------------------------- 2.6/124.9 MB 2.5 MB/s eta 0:00:50
   - -------------------------------------- 3.1/124.9 MB 2.6 MB/s eta 0:00:47
   - -------------------------------------- 4.2/124.9 MB 2.9 MB/s eta 0:00:42
   - -------------------------------------- 5.2/124.9 MB 3.2 MB/s eta 0:00:38
   -- ------------------------------------- 6.6/124.9 MB 3.5 MB/s eta 0:00:35
   -- ------------------------------------- 7.9/124.9 MB 3.8 MB/s eta 0:00:32
   --- ------------------------------------ 9.4/124.9 MB 4.1 MB/s eta 0:00:29
   --- ------------------------------------ 11.5/124.9 MB 4.5 MB/s eta 0:00:26
   ---- ----------------------------------- 13.4/124.9 MB 4.8 MB/s eta 0:00:24
   ---- ----------------------------------- 14.9/124.9 MB 5.0 MB/s eta 0:00:23
   ----- ---------------------------------- 16.5/124.9 MB 5.2 MB/s eta 0:00:21
   ----- ---------------------------------- 18.4/124.9 MB 5.4 MB/s eta 0:00:20
   ------ --------------------------------- 20.2/124.9 MB 5.5 MB/s eta 0:00:19
   ------- -------------------------------- 22.0/124.9 MB 5.7 MB/s eta 0:00:19
   ------- -------------------------------- 23.6/124.9 MB 5.8 MB/s eta 0:00:18
   -------- ------------------------------- 25.4/124.9 MB 5.9 MB/s eta 0:00:17
   -------- ------------------------------- 27.3/124.9 MB 6.1 MB/s eta 0:00:17
   --------- ------------------------------ 28.8/124.9 MB 6.2 MB/s eta 0:00:16
   --------- ------------------------------ 30.7/124.9 MB 6.2 MB/s eta 0:00:16
   ---------- ----------------------------- 32.5/124.9 MB 6.3 MB/s eta 0:00:15
   ---------- ----------------------------- 34.3/124.9 MB 6.4 MB/s eta 0:00:15
   ----------- ---------------------------- 36.2/124.9 MB 6.5 MB/s eta 0:00:14
   ------------ --------------------------- 38.0/124.9 MB 6.6 MB/s eta 0:00:14
   ------------ --------------------------- 39.8/124.9 MB 6.6 MB/s eta 0:00:13
   ------------- -------------------------- 41.7/124.9 MB 6.7 MB/s eta 0:00:13
   ------------- -------------------------- 43.5/124.9 MB 6.8 MB/s eta 0:00:13
   -------------- ------------------------- 45.4/124.9 MB 6.8 MB/s eta 0:00:12
   --------------- ------------------------ 47.2/124.9 MB 6.9 MB/s eta 0:00:12
   --------------- ------------------------ 49.0/124.9 MB 6.9 MB/s eta 0:00:11
   ---------------- ----------------------- 50.9/124.9 MB 7.0 MB/s eta 0:00:11
   ---------------- ----------------------- 53.0/124.9 MB 7.0 MB/s eta 0:00:11
   ----------------- ---------------------- 54.8/124.9 MB 7.1 MB/s eta 0:00:10
   ------------------ --------------------- 56.6/124.9 MB 7.1 MB/s eta 0:00:10
   ------------------ --------------------- 58.5/124.9 MB 7.2 MB/s eta 0:00:10
   ------------------- -------------------- 60.6/124.9 MB 7.2 MB/s eta 0:00:09
   ------------------- -------------------- 62.4/124.9 MB 7.2 MB/s eta 0:00:09
   -------------------- ------------------- 64.2/124.9 MB 7.3 MB/s eta 0:00:09
   --------------------- ------------------ 66.1/124.9 MB 7.3 MB/s eta 0:00:09
   --------------------- ------------------ 67.9/124.9 MB 7.3 MB/s eta 0:00:08
   ---------------------- ----------------- 69.7/124.9 MB 7.4 MB/s eta 0:00:08
   ---------------------- ----------------- 71.3/124.9 MB 7.4 MB/s eta 0:00:08
   ----------------------- ---------------- 73.1/124.9 MB 7.4 MB/s eta 0:00:07
   ------------------------ --------------- 75.0/124.9 MB 7.4 MB/s eta 0:00:07
   ------------------------ --------------- 76.8/124.9 MB 7.5 MB/s eta 0:00:07
   ------------------------- -------------- 78.6/124.9 MB 7.5 MB/s eta 0:00:07
   ------------------------- -------------- 80.5/124.9 MB 7.5 MB/s eta 0:00:06
   -------------------------- ------------- 82.3/124.9 MB 7.5 MB/s eta 0:00:06
   -------------------------- ------------- 84.1/124.9 MB 7.6 MB/s eta 0:00:06
   --------------------------- ------------ 86.0/124.9 MB 7.6 MB/s eta 0:00:06
   ---------------------------- ----------- 87.8/124.9 MB 7.6 MB/s eta 0:00:05
   ---------------------------- ----------- 89.9/124.9 MB 7.6 MB/s eta 0:00:05
   ----------------------------- ---------- 91.8/124.9 MB 7.6 MB/s eta 0:00:05
   ----------------------------- ---------- 93.3/124.9 MB 7.7 MB/s eta 0:00:05
   ------------------------------ --------- 95.4/124.9 MB 7.7 MB/s eta 0:00:04
   ------------------------------- -------- 97.3/124.9 MB 7.7 MB/s eta 0:00:04
   ------------------------------- -------- 99.1/124.9 MB 7.7 MB/s eta 0:00:04
   -------------------------------- ------- 100.9/124.9 MB 7.7 MB/s eta 0:00:04
   -------------------------------- ------- 102.8/124.9 MB 7.7 MB/s eta 0:00:03
   --------------------------------- ------ 104.1/124.9 MB 7.8 MB/s eta 0:00:03
   ---------------------------------- ----- 106.4/124.9 MB 7.8 MB/s eta 0:00:03
   ---------------------------------- ----- 108.3/124.9 MB 7.8 MB/s eta 0:00:03
   ----------------------------------- ---- 110.1/124.9 MB 7.8 MB/s eta 0:00:02
   ----------------------------------- ---- 111.9/124.9 MB 7.8 MB/s eta 0:00:02
   ------------------------------------ --- 113.8/124.9 MB 7.8 MB/s eta 0:00:02
   ------------------------------------- -- 115.9/124.9 MB 7.8 MB/s eta 0:00:02
   ------------------------------------- -- 117.7/124.9 MB 7.9 MB/s eta 0:00:01
   -------------------------------------- - 119.5/124.9 MB 7.9 MB/s eta 0:00:01
   -------------------------------------- - 121.4/124.9 MB 7.9 MB/s eta 0:00:01
   -------------------------------------- - 121.6/124.9 MB 7.9 MB/s eta 0:00:01
   -------------------------------------- - 121.6/124.9 MB 7.9 MB/s eta 0:00:01
   ---------------------------------------  122.2/124.9 MB 7.7 MB/s eta 0:00:01
   ---------------------------------------  122.2/124.9 MB 7.7 MB/s eta 0:00:01
   ---------------------------------------  122.2/124.9 MB 7.7 MB/s eta 0:00:01
   ---------------------------------------  122.2/124.9 MB 7.7 MB/s eta 0:00:01
   ---------------------------------------  122.2/124.9 MB 7.7 MB/s eta 0:00:01
   ---------------------------------------  122.7/124.9 MB 7.2 MB/s eta 0:00:01
   ---------------------------------------  123.7/124.9 MB 7.2 MB/s eta 0:00:01
   ---------------------------------------  124.0/124.9 MB 7.1 MB/s eta 0:00:01
   ---------------------------------------  124.0/124.9 MB 7.1 MB/s eta 0:00:01
   ---------------------------------------  124.8/124.9 MB 7.0 MB/s eta 0:00:01
   ---------------------------------------  124.8/124.9 MB 7.0 MB/s eta 0:00:01
   ---------------------------------------- 124.9/124.9 MB 6.8 MB/s eta 0:00:00
Installing collected packages: xgboost
Successfully installed xgboost-2.1.3

In [21]:
data = pd.read_csv(r"J:\ML Algorithms\ML-Projects\Linear Regression\DataSets\Sales Forecastes.csv")

In [22]:
data.head()

         date  store  item  sales
0  2013-01-01      1     1     13
1  2013-01-02      1     1     11
2  2013-01-03      1     1     14
3  2013-01-04      1     1     13
4  2013-01-05      1     1     10

In [27]:
data.describe()

               store           item          sales
count  913000.000000  913000.000000  913000.000000
mean        5.500000      25.500000      52.250287
std         2.872283      14.430878      28.801144
min         1.000000       1.000000       0.000000
25%         3.000000      13.000000      30.000000
50%         5.500000      25.500000      47.000000
75%         8.000000      38.000000      70.000000
max        10.000000      50.000000     231.000000

Check for non null values in the dataset

In [24]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 913000 entries, 0 to 912999
Data columns (total 4 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   date    913000 non-null  object
 1   store   913000 non-null  int64
 2   item    913000 non-null  int64
 3   sales   913000 non-null  int64
dtypes: int64(3), object(1)
memory usage: 27.9+ MB

In [28]:
data.describe()

               store           item          sales
count  913000.000000  913000.000000  913000.000000
mean        5.500000      25.500000      52.250287
std         2.872283      14.430878      28.801144
min         1.000000       1.000000       0.000000
25%         3.000000      13.000000      30.000000
50%         5.500000      25.500000      47.000000
75%         8.000000      38.000000      70.000000
max        10.000000      50.000000     231.000000

Drop Store and items document